/* Generated By:JavaCC: Do not edit this line. StreamProvider.java Version 6.1 */
/* JavaCCOptions:KEEP_LINE_COLUMN=true */
package us.kbase.moduleservice.gwt.client.parser;


import java.io.IOException;

/**
 * NOTE : This generated class can be safely deleted if installing in a GWT installation (use StringProvider instead)
 */
public class StreamProvider implements Provider {

	@Override
	public int read(char[] buffer, int off, int len) throws IOException {
		throw new IOException("This implementation is not supported in GWT mode");
	}

	@Override
	public void close() throws IOException {
		throw new IOException("This implementation is not supported in GWT mode");
	}

}

/* JavaCC - OriginalChecksum=ab7f995631fdae52e9503ae42925ed66 (do not edit this line) */
